#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <queue>
#include <unordered_map>
#include <algorithm>
#include <chrono>
#include <iomanip>
#include <limits>
using namespace std; using Clock=chrono::high_resolution_clock;
struct Edge{int to,w;}; using Graph=unordered_map<int,vector<Edge>>; struct RunResult{long long edges; size_t nodes; double loadTime; double algoTime; int source,target,distance; vector<int> path;};
static double secs(Clock::time_point a,Clock::time_point b){return chrono::duration<double>(b-a).count();}
void addEdge(Graph& g,int u,int v){g[u].push_back({v,1}); g[v].push_back({u,1});}
Graph loadGraph(const string& fileName,long long maxEdges,long long& edgeCount,double& loadTime){auto st=Clock::now(); ifstream file(fileName); if(!file) throw runtime_error("Could not open dataset. Use unzipped as-skitter.txt."); Graph g; string line; edgeCount=0; while(getline(file,line)){ if(line.empty()||line[0]=='#') continue; stringstream ss(line); int u,v; if(ss>>u>>v){addEdge(g,u,v); edgeCount++;} if(maxEdges>0&&edgeCount>=maxEdges) break;} loadTime=secs(st,Clock::now()); return g;}
vector<int> buildPath(int s,int t,const unordered_map<int,int>& prev){vector<int> p; int cur=t; p.push_back(cur); while(cur!=s){auto it=prev.find(cur); if(it==prev.end()) return {}; cur=it->second; p.push_back(cur);} reverse(p.begin(),p.end()); return p;}
int heuristic(int,int){return 0;} // no coordinates in as-Skitter, so admissible heuristic is 0
RunResult runAStar(const string& file,int source,long long maxEdges){long long edgeCount; double loadTime; Graph g=loadGraph(file,maxEdges,edgeCount,loadTime); if(!g.count(source)) throw runtime_error("Source node not found."); int target=0; for(auto& kv:g) target=max(target,kv.first); const int INF=numeric_limits<int>::max()/4; unordered_map<int,int> gScore,prev; gScore.reserve(g.size()); prev.reserve(g.size()); for(auto& kv:g) gScore[kv.first]=INF; gScore[source]=0; using Item=pair<int,int>; priority_queue<Item,vector<Item>,greater<Item>> open; open.push({heuristic(source,target),source}); auto st=Clock::now(); while(!open.empty()){auto [f,u]=open.top(); open.pop(); if(u==target) break; for(auto &e:g[u]){int tentative=gScore[u]+e.w; if(tentative<gScore[e.to]){gScore[e.to]=tentative; prev[e.to]=u; open.push({tentative+heuristic(e.to,target),e.to});}}} double algo=secs(st,Clock::now()); auto path=buildPath(source,target,prev); int d=gScore.count(target)?gScore[target]:INF; return {edgeCount,g.size(),loadTime,algo,source,target,d,path};}
void makeSvgBar(const string& filename,const string& title,const string& label,double value,const string& unit){ofstream out(filename); int bar=(int)(500*(value/max(1.0,value))); out<<"<svg xmlns='http://www.w3.org/2000/svg' width='800' height='300'><rect width='100%' height='100%' fill='white'/><text x='30' y='40' font-size='24' font-family='Arial'>"<<title<<"</text><text x='30' y='100' font-size='18' font-family='Arial'>"<<label<<"</text><rect x='200' y='75' width='"<<bar<<"' height='50' fill='steelblue'/><text x='"<<210+bar<<"' y='108' font-size='16' font-family='Arial'>"<<fixed<<setprecision(4)<<value<<" "<<unit<<"</text></svg>";}
void saveOutputs(const RunResult&r){ofstream csv("results.csv"); csv<<"algorithm,edges,nodes,load_time_seconds,algorithm_time_seconds,total_time_seconds,source,target,distance,path_length\n"; csv<<"A*,"<<r.edges<<","<<r.nodes<<","<<r.loadTime<<","<<r.algoTime<<","<<r.loadTime+r.algoTime<<","<<r.source<<","<<r.target<<","<<r.distance<<","<<r.path.size()<<"\n"; makeSvgBar("runtime_graph.svg","A* Runtime","Algorithm time",r.algoTime,"seconds"); makeSvgBar("path_length_graph.svg","A* Path Length","Path length",(double)r.path.size(),"nodes");}
int main(int argc,char* argv[]){try{string file="as-skitter.txt"; int source=0; long long maxEdges=0; if(argc>=2) file=argv[1]; if(argc>=3) source=stoi(argv[2]); if(argc>=4) maxEdges=stoll(argv[3]); cout<<"=============================================\nA* Search Algorithm Project\nStanford SNAP as-Skitter Dataset\n=============================================\n\n"; auto r=runAStar(file,source,maxEdges); cout<<"Nodes Loaded       : "<<r.nodes<<"\nEdges Loaded       : "<<r.edges<<"\nGraph Load Time    : "<<fixed<<setprecision(4)<<r.loadTime<<" seconds\n"; cout<<"A* Time            : "<<r.algoTime<<" seconds\nTotal Runtime      : "<<r.loadTime+r.algoTime<<" seconds\nSource Node        : "<<r.source<<"\nTarget Node        : "<<r.target<<"\nDistance           : "<<r.distance<<" edge(s)\nPath               : "; if(r.path.empty()) cout<<"unreachable"; else for(size_t i=0;i<r.path.size();i++) cout<<r.path[i]<<(i+1<r.path.size()?" -> ":""); cout<<"\n\nNote: as-Skitter has no coordinates, so h(n)=0. This makes A* behave like Dijkstra but still shows the A* structure.\nTime Complexity    : O((V + E) log V) with this priority queue implementation\nSpace Complexity   : O(V + E)\n"; saveOutputs(r); cout<<"\nCreated results.csv, runtime_graph.svg, and path_length_graph.svg\n";}catch(const exception&e){cerr<<"Error: "<<e.what()<<"\n"; return 1;}}
